baseURL = "/"
languageCode = "en-us"
title = "Le Château. Tiers-lieu habité et Laboratoire de création culturelle : pour accueillir le monde entier. Porté par l'association Tedua et ..."
disableKinds = ["sitemap", "RSS"]
theme = "reveal-hugo"

# uncomment for browsing at file:///
# relativeURLs = true
# uglyURLs = true

[author]
name = "Josh Dzielak"

# currently only the unsafe mode for goldmark is supported
[markup.goldmark.renderer]
unsafe = true

# choose between Hugo compile-time or Highlight.js
# syntax highlighting for code inside of code fences
[markup.highlight]
codeFences = false  # use highlight.js 
# codeFences = true  # use hugo highlighting at compile time
style = "tango"  # set a style for hugo highlighting

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
#theme= "moon"
#custom_theme = "reveal-hugo/themes/robot-lung.css"
#custom_theme_compile = true

history = true
slide_number = true
transition_speed = 'fast'

# used in content/template-example
[params.reveal_hugo.templates.grey]
background = "#424242"
transition = "convex"
